mode: "train"
# train, cross_val, grid_search, save

using_model: 'LinearRegression'
model_save_path: 'models/best_model.pdk'

models:
  LinearRegression: {}
  RandomForestRegressor: {}
  Ridge: {}
  Lasso: {}
  GradientBoostingRegressor: {}

cross_val:
  KFold: 
    n_splits: 10
    shuffle: True
    random_state: 42
  scoring: 'r2_score'

grid_search:
  cv: 5
  scoring: 'r2_score'
  param_grid: 


data:
  X_train_path: 'data/processed/X_train.csv'
  y_train_path: 'data/processed/y_train.csv'


preprocess:
  scale_cols: ["alcohol", "pH", "density", "citric acid", "sulphates", "fixed acidity", "volatile acidity"]
  log_cols: ["residual sugar", "chlorides", "total sulfur dioxide", "free sulfur dioxide"]
  

